Homework 06/Models/order_items.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework_06.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class order_items
    {
        public int order_id { get; set; }
        public int item_id { get; set; }
        public int product_id { get; set; }
        [DisplayName("Quantity")]
        public int quantity { get; set; }
        [DisplayName("List Price")]
        public decimal list_price { get; set; }
        public decimal discount { get; set; }
    
        public virtual product product { get; set; }
        public virtual order order { get; set; }
    }
}

Homework 06/Controllers/order_itemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Homework_06.Models;
using PagedList.Mvc;
using PagedList;


namespace Homework_06.Controllers
{
    public class order_itemsController : Controller
    {
        private BikeStoresEntities db = new BikeStoresEntities();

        // GET: order_items
        [HttpGet]
        public ActionResult Index(DateTime? DateString, int? i)
        {



            DateString = DateTime.MinValue;

            ViewData["DateFilter"] = DateString;



            var order_items = db.order_items.Include(o => o.product).Include(a => a.order).OrderByDescending(o => o.order.order_date == DateString ).ToList();
            //return View(order_items.ToList().ToPagedList(i ?? 1, 10));



            return View(order_items.ToList().ToPagedList(i ?? 1, 25));




        }




        public ActionResult DateFilter(string date)
        {
            var dateTime = Convert.ToDateTime(date);

            var datum = db.order_items.Include(o => o.product).Include(a => a.order).OrderByDescending(o => o.order.order_date == dateTime).ToList();


            //var tran = from transaction in transactions
            //           where transaction.OccassionDate.ToShortDateString() == dateTime
            //           select transaction;


            return PartialView("Index", datum);
        }


        [HttpPost]
        public ActionResult Index(string Datepicker)
        {
            ViewBag.DateValue = Datepicker;
            return View();
        }































        // GET: order_items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order_items order_items = db.order_items.Find(id);
            if (order_items == null)
            {
                return HttpNotFound();
            }
            return View(order_items);
        }

        // GET: order_items/Create
        public ActionResult Create()
        {
            ViewBag.product_id = new SelectList(db.products, "product_id", "product_name");
            ViewBag.order_id = new SelectList(db.orders, "order_id", "order_id");
            return View();
        }

        // POST: order_items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "order_id,item_id,product_id,quantity,list_price,discount")] order_items order_items)
        {
            if (ModelState.IsValid)
            {
                db.order_items.Add(order_items);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.product_id = new SelectList(db.products, "product_id", "product_name", order_items.product_id);
            ViewBag.order_id = new SelectList(db.orders, "order_id", "order_id", order_items.order_id);
            return View(order_items);
        }

        // GET: order_items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order_items order_items = db.order_items.Find(id);
            if (order_items == null)
            {
                return HttpNotFound();
            }
            ViewBag.product_id = new SelectList(db.products, "product_id", "product_name", order_items.product_id);
            ViewBag.order_id = new SelectList(db.orders, "order_id", "order_id", order_items.order_id);
            return View(order_items);
        }

        // POST: order_items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "order_id,item_id,product_id,quantity,list_price,discount")] order_items order_items)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order_items).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.product_id = new SelectList(db.products, "product_id", "product_name", order_items.product_id);
            ViewBag.order_id = new SelectList(db.orders, "order_id", "order_id", order_items.order_id);
            return View(order_items);
        }

        // GET: order_items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            order_items order_items = db.order_items.Find(id);
            if (order_items == null)
            {
                return HttpNotFound();
            }
            return View(order_items);
        }

        // POST: order_items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            order_items order_items = db.order_items.Find(id);
            db.order_items.Remove(order_items);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Homework 06/Views/order_items/Create.cshtml
@model Homework_06.Models.order_items

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>order_items</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.order_id, "order_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("order_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.order_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.item_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.item_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.item_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_id, "product_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("product_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.product_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.list_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.list_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.list_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.discount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.discount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.discount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Homework 06/Views/order_items/Delete.cshtml
@model Homework_06.Models.order_items

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>order_items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.list_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.list_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order.order_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order.order_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Homework 06/Views/order_items/Details.cshtml
@model Homework_06.Models.order_items

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>order_items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.list_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.list_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.product.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order.order_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order.order_id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Homework 06/Views/order_items/Edit.cshtml
@model Homework_06.Models.order_items

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>order_items</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.order_id)

        @Html.HiddenFor(model => model.item_id)

        <div class="form-group">
            @Html.LabelFor(model => model.product_id, "product_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("product_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.product_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.list_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.list_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.list_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.discount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.discount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.discount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Homework 06/Views/order_items/Index.cshtml
@model PagedList.IPagedList<Homework_06.Models.order_items>

@{
    ViewBag.Title = "Index";
}


@using PagedList.Mvc;
@using PagedList;


<h2>Orders</h2>
















@*@{
    ViewBag.Title = "Use of jQuery Datepicker In an MVC Application";
}
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script>
    $(function () {
        $("#1Search").datepicker();
    });
</script>
<h2>jQuery Datepicker</h2>
@using (Html.BeginForm("Index", "order_items"))
{
    <p>
        @Html.TextBox("Datepicker", "", new { @id = "txtdatepicker", @style = "width:150px;" })
        <br />
        Your selected date :@ViewBag.DateValue
        <br /><input type="submit" value="Submit" />
    </p>
}*@



























@*///////////////////////////////////////////////////////////////////////////////*@





<label>
    Search by Date:
    <input type="date" name="DateString" placeholder="Search" id="1Search" value="datum" aria-label="Search" required pattern="\d{4}-\d{2}-\d{2}" />
    <span class="validity"></span>
    <button class="btn btn-primary" type="submit" value="1Search">Search</button>
</label>



@*<script>
    $("#1Search").datepicker({
        $.get("/order_items/DateFilter", { "date": date }).done(function (result) {
            $('#myDiv').html(result);
        }
    });
</script>

<div id="myDiv">

    <button class="btn btn-primary" type="submit" value="Search">Search</button>

</div>*@

<form asp-action="Index" method="get">


    @*<label>
            Search by Date:
            <input type="date" name="DateString" placeholder="Search" id="1Search" value="datum" aria-label="Search" required pattern="\d{4}-\d{2}-\d{2}" />
            <span class="validity"></span>
            <button class="btn btn-primary" type="submit" value="1Search">Search</button>
        </label>*@


    @*@(Html.Kendo().DatePickerFor(x => x.myStartDate)
        .HtmlAttributes( new {id="startDate", style = "width:252px;"}))*@


</form>



@{
    var asbwerk  = Model.GroupBy(x => x.order).Select(x => new { order_id = x.Key, product = x });

    var werktog = Model.GroupBy(x => x.order).Select(x => new { order_date = x.Key, product = x }).ToList();
}



<div>
    @foreach (var order_bucket in asbwerk)
    {





        <table class="table">
            <tr>

                <th>
                    @Html.DisplayNameFor(model => model.First().product.product_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().list_price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().quantity)
                </th>
                <td>
                    <b>Total</b>
                </td>



                <th></th>
            </tr>


            @{

                decimal total = 0;
                decimal Grandtotal = 0;




            }



            <p>Order @order_bucket.order_id.order_id - @order_bucket.order_id.order_date.ToString("yyyy/MM/dd")  </p>
            @foreach (var item in order_bucket.product)

            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.product.product_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.list_price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.quantity)
                    </td>
                    <td>
                        @{

                            total = item.product.list_price * item.quantity;
                            Grandtotal = total + Grandtotal;


                        }



                        @total
                    </td>


                </tr>
            }
            <tr>
                <td>
                </td>
                <td>
                </td>
                <td>
                    <p><I>Grand Total:</I></p>
                </td>
                <td>
                    <p><I>@Grandtotal</I></p>
                </td>
            </tr>
        </table>

    }
</div>









@Html.PagedListPager(Model, i => Url.Action("Index", "order_items", new { i, DateString = Request.QueryString["DateString"] }))