Homework 06/Models/product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework_06.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_items = new HashSet<order_items>();
            this.stocks = new HashSet<stock>();
        }
    
        public int product_id { get; set; }
        [DisplayName("Name")]
        public string product_name { get; set; }
        public int brand_id { get; set; }
        public int category_id { get; set; }
        [DisplayName("Year")]
        public short model_year { get; set; }
        [DisplayName("Price")]
        public decimal list_price { get; set; }
        
        public virtual brand brand { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock> stocks { get; set; }
    }
}

Homework 06/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Homework_06.Models;
using PagedList.Mvc;
using PagedList;




namespace Homework_06.Controllers
{
    public class productsController : Controller
    {
        private BikeStoresEntities db = new BikeStoresEntities();

        // GET: products
        public ActionResult Index(string SearchString, int? i)
        {


            SearchString = (SearchString == null) ? "" : SearchString;

            ViewData["CurrentFilter"] = SearchString;

            var products = db.products.Include(p => p.brand).Include(p => p.category).OrderByDescending(p => p.product_name.Contains(SearchString));



            return View(products.ToList().ToPagedList(i ?? 1, 10));
            //return View(products.ToList());

        }






        // GET: products/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    product product = db.products.Find(id);
        //    if (product == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(product);
        //}

        // GET: products/Create
        //public ActionResult Create()
        //{
        //    ViewBag.brand_id = new SelectList(db.brands, "brand_id", "brand_name");
        //    ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name");
        //    return View();
        //}

        // POST: products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "product_id,product_name,brand_id,category_id,model_year,list_price")] product product)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.products.Add(product);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.brand_id = new SelectList(db.brands, "brand_id", "brand_name", product.brand_id);
        //    ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", product.category_id);
        //    return View(product);
        //}

        // GET: products/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    product product = db.products.Find(id);
        //    if (product == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.brand_id = new SelectList(db.brands, "brand_id", "brand_name", product.brand_id);
        //    ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", product.category_id);
        //    return View(product);
        //}

        // POST: products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "product_id,product_name,brand_id,category_id,model_year,list_price")] product product)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(product).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.brand_id = new SelectList(db.brands, "brand_id", "brand_name", product.brand_id);
        //    ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", product.category_id);
        //    return View(product);
        //}

        // GET: products/Delete/5
        //public ActionResult Delete(int? id)
        ////{
        ////    if (id == null)
        ////    {
        ////        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        ////    }
        ////    product product = db.products.Find(id);
        ////    if (product == null)
        ////    {
        ////        return HttpNotFound();
        ////    }
        ////    return View(product);
        ////}

        //// POST: products/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    product product = db.products.Find(id);
        //    db.products.Remove(product);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}



        public ActionResult Details(int? id)
        {

            if (Request.IsAjaxRequest())
            {
                product product = db.products.Find(id);
                if (product != null)
                {
                    return PartialView(product);
                }
                else
                {
                    Response.StatusCode = 403;
                    return PartialView("Error");
                }
            }
            Response.StatusCode = 500;
            return PartialView("Error");


        }





        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///





        private BikeStoresEntities _context;
        public productsController()
        {
            _context = new BikeStoresEntities();
        }
        
        public JsonResult List()
        {
            return Json(_context.Product.ToList(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Add(product user)
        {
            _context.Product.Add(user);
            _context.SaveChanges();
            return Json(JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetbyID(int ID)
        {
            return Json(_context.Product.FirstOrDefault(x => x.product_id == ID), JsonRequestBehavior.AllowGet);
        }
        public JsonResult Update(product user)
        {
            var data = _context.Product.FirstOrDefault(x => x.product_id == user.product_id);
            if (data != null)
            {
                data.product_name = user.product_name;
                data.model_year = user.model_year;
                data.list_price = user.list_price;
                data.brand = user.brand;
                data.category = user.category;
                _context.SaveChanges();
            }
            return Json(JsonRequestBehavior.AllowGet);
        }
        public JsonResult Delete(int ID)
        {
            var data = _context.Product.FirstOrDefault(x => x.product_id == ID);
            _context.Product.Remove(data);
            _context.SaveChanges();
            return Json(JsonRequestBehavior.AllowGet);
        }




    }
}

Homework 06/Views/products/Create.cshtml
@model Homework_06.Models.product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.product_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.product_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.brand_id, "brand_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("brand_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.brand_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model_year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.model_year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.model_year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.list_price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.list_price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.list_price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Homework 06/Views/products/Delete.cshtml
@model Homework_06.Models.product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.model_year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.model_year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.list_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.list_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.brand.brand_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brand.brand_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category.category_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category.category_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Homework 06/Views/products/Details.cshtml
@model Homework_06.Models.product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.product_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.product_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.model_year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.model_year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.list_price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.list_price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.brand.brand_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brand.brand_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category.category_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category.category_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.product_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>



<table class="table">
    <tr>
        <th>Store</th>
        <th>Quantity</th>
    </tr>
    <tr>

        <td>Santa Cruz Bikes</td>
        <td>
            @{var total = 0; string message = "";
                foreach (var item in Model.stocks)
                {


                    if (item.product_id == Model.product_id && item.store_id == 1)
                    {

                        total = (int)item.quantity;
                        if (total == 0)
                        {
                            message = "Out of Stock";
                        }


                        else
                        {
                            message = total.ToString();
                        }
                    }
                }
            }
            @message
        </td>
    </tr>
    <tr>
        <td>Baldwin Bikes</td>
        <td>
            @{
                foreach (var item in Model.stocks)
                {



                    if (item.product_id == Model.product_id && item.store_id == 2)
                    {



                        total = (int)item.quantity;
                        if (total == 0)
                        {

                            message = "Out of Stock";
                        }
                        else
                        {
                            message = total.ToString();
                        }
                    }
                }
            }
            @message
        </td>
    </tr>
    <tr>
        <td>Santa Cruz Bike</td>
        <td>
            @{
                foreach (var item in Model.stocks)
                {





                    if (item.product_id == Model.product_id && item.store_id == 3)
                    {
                        total = (int)item.quantity;
                        if (total == 0)
                        {
                            message = "Out of Stock";
                        }


                        else
                        {
                            message = total.ToString();
                        }
                    }
                }
            }
            @message
        </td>
    </tr>
</table>

Homework 06/Views/products/Index.cshtml
@model PagedList.IPagedList<Homework_06.Models.product>

@using PagedList.Mvc;
@using PagedList;

@{
    ViewBag.Title = "Index";
}


<h2>Products</h2>


<form asp-action="Index" method="get">
    <div class="row">
        <input class="col-sm-1 form-control mr-sm-2" type="text" placeholder="Search" name="SearchString" value="@ViewData["CurrentFilter"]" aria-label="Search">



        <button class="col-sm-1 btn btn-primary my-2 my-sm-0" type="submit" value="Search">Search</button>

        <button class="col-sm-1 btn btn-danger my-2 my-sm-0" type="submit">@Html.ActionLink("Clear", "Index", "products", null, new { style = "color: white" })</button>

        @*<button type="submit" class="col-sm-1 btn btn-info my-2 my-sm-0">@Html.ActionLink("Create New", "Create")</button>*@

        @*<div class="4AddPopUp col-sm-1 btn btn-info my-2 my-sm-0" type="button" target="#myModal">
                @Html.Label("Create")
            </div>
            <div class="modal fade" id="CreatePopUp" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-body">


                    </div>
                </div>
            </div>*@


        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal1" onclick="clearTextBox();">Create</button><br /><br />

    </div>
</form>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().product_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().model_year)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().list_price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().brand.brand_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().category.category_name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.product_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.model_year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.list_price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.brand.brand_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.category.category_name)
            </td>
            <td>

                @*<button type="button">@Html.ActionLink("Edit", "Edit", new { id = item.product_id, style = "color: white" })</button>*@





                <div class="1AddPopUp btn btn-primary my-2 my-sm-0" type="button">
                    @Html.Label("Edit")
                </div>
                <div class="modal fade" id="EdPopUp" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-body">
                                
                                    <form>
                                        <div class="form-group">
                                            <label for="Name">Name</label>
                                            <input type="text" class="form-control" id="Name" placeholder="Name" />
                                        </div>
                                        <div class="form-group">
                                            <label for="Year">Year</label>
                                            <input type="text" class="form-control" id="Year" placeholder="Year" />
                                        </div>
                                        <div class="form-group">
                                            <label for="Price">Price</label>
                                            <input type="text" class="form-control" id="Price" placeholder="Price" />
                                        </div>
                                        <div class="form-group">
                                            <label for="Country">Brand</label>
                                            <input type="text" class="form-control" id="Brand" placeholder="Brand" />
                                        </div>
                                        <div class="form-group">
                                            <label for="Country">Category</label>
                                            <input type="text" class="form-control" id="Category" placeholder="Category" />
                                        </div>
                                    </form>
                                
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" id="btnAdd" onclick="return Add();">Add</button>
                                    @*<button type="button" class="btn btn-primary" id="btnUpdate" style="display:none;" onclick="Update();">Update</button>*@
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>







                @*<input class="btn btn-info" type="button" value="Details" id="@item.product_id" onclick="Details(this.id)" />*@



                |

                @*<button type="button">@Html.ActionLink("Details", "Details", new { id = item.product_id, style = "color: white" })</button>*@



                <div class=" btn btn-info " type="button" value="Details" id="@item.product_id" onclick="Details(this.id)">

                    @Html.Label("Details")

                </div>
                <div class="modal fade" id="DetailPopUp" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-body">
                                Details goed
                            </div>
                        </div>
                    </div>
                </div>




                |
                @*<button type="button">@Html.ActionLink("Delete", "Delete", new { id = item.product_id, style = "color: white" })</button>*@


                <div class="3AddPopUp btn btn-danger my-2 my-sm-0" type="button">
                    @Html.Label("Delete")
                </div>
                <div class="modal fade" id="DelPopUp" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-body">
                                Are you sure you want to delete this Record?
                            </div>
                            <button type="button" class="btn btn-primary" id="btnAdd" onclick="return Add();">Delete</button>
                            @*<button type="button" class="btn btn-primary" id="btnUpdate" style="display:none;" onclick="Update();">Update</button>*@
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>




                


            </td>
        </tr>
    }

</table>




<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title" id="myModalLabel">Add Product</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="Name">Name</label>
                        <input type="text" class="form-control" id="Name" placeholder="Name" />
                    </div>
                    <div class="form-group">
                        <label for="Year">Year</label>
                        <input type="text" class="form-control" id="Year" placeholder="Year" />
                    </div>
                    <div class="form-group">
                        <label for="Price">Price</label>
                        <input type="text" class="form-control" id="Price" placeholder="Price" />
                    </div>
                    <div class="form-group">
                        <label for="Country">Brand</label>
                        <input type="text" class="form-control" id="Brand" placeholder="Brand" />
                    </div>
                    <div class="form-group">
                        <label for="Country">Category</label>
                        <input type="text" class="form-control" id="Category" placeholder="Category" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAdd" onclick="return Add();">Add</button>
                @*<button type="button" class="btn btn-primary" id="btnUpdate" style="display:none;" onclick="Update();">Update</button>*@
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/Users.js"></script>





@*//////////////////////////////////////////////////////////////////////////////*@

@*@section Scripts{
        <script type="text/javascript">
            $(document).ready(function () {
                $(".1AddPopUp").click(function (e) {
                    $('#EdPopUp').modal('show');
                });
            });
        </script>*@



        @*<script type="text/javascript">
            $(document).ready(function () {
                $(".myModal").click(function (e) {
                    $('#btnUpdate').modal('show');
                });
            });
        </script>*@



        @*<script type="text/javascript">
            $(document).ready(function () {
                $(".3AddPopUp").click(function (e) {
                    $('#DelPopUp').modal('show');
                });
            });
        </script>



        <script type="text/javascript">
            $(document).ready(function () {
                $(".4AddPopUp").click(function (e) {
                    $('#CreatePopUp').modal('show');
                });
            });
        </script>*@





    @*}*@




<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>

        function Details(id) {
            $.get("@Url.Action("Details", "products")/" + id,
                function (data) { $('.modal-body').html(data); })
            $('#myModal').modal('show');
        }

        $('#myModal').on('hidden.bs.modal', function (e) {
            $('.modal-body').html("");
        })



        function Update(User) {
            $.get("@Url.Action("Update", "products")/" + id,
                function (data) { $('.modal-body').html(data); })
            $('#myModal1').modal('show');
        }

        $('#myModal1').on('hidden.bs.modal', function (e) {
            $('.modal-body').html("");
        })





            $(document).ready(function () {
                $(".1AddPopUp").click(function (e) {
                    $('#EdPopUp').modal('show');
                });
            });

        $(document).ready(function () {
            $(".3AddPopUp").click(function (e) {
                $('#DelPopUp').modal('show');
            });
        });

        $(document).ready(function () {
            $(".2AddPopUp").click(function (e) {
                $('#btnUpdate').modal('show');
            });
        });


    </script>
}



@Html.PagedListPager(Model, i => Url.Action("Index", "products", new { i, SearchString = Request.QueryString["SearchString"] }))

<script src="~/Scripts/Product.js"></script>

Homework 06/Views/products/Search.cshtml
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>